<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>1755ba13-ede9-42a1-b4fe-7d2d6692b323</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/section[1]/div[1]/div[2]/table[1]/tbody[1]/tr[1]/td[6]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#product-2 [class="cart_quantity_delete"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>