<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>8a50ecc3-b70d-45e7-b3e2-2a70b8e41f8c</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_women</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/section[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/h4[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="panel\ panel-default"]:nth-child(1) &gt; [class="panel-heading"] a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'WOMEN')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>WOMEN</value>
        <webElementGuid>c7cec82f-66f5-424c-a7c1-bdaa945c6388</webElementGuid>
    </webElementProperties>
</WebElementEntity>